// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: any.proto

// Protobuf Java Version: 3.25.3
package proto;

public final class AnyProto {
  private AnyProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface AnyOrBuilder extends
      // @@protoc_insertion_point(interface_extends:proto.Any)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string procCode = 1;</code>
     * @return The procCode.
     */
    java.lang.String getProcCode();
    /**
     * <code>string procCode = 1;</code>
     * @return The bytes for procCode.
     */
    com.google.protobuf.ByteString
        getProcCodeBytes();

    /**
     * <code>string taskCode = 2;</code>
     * @return The taskCode.
     */
    java.lang.String getTaskCode();
    /**
     * <code>string taskCode = 2;</code>
     * @return The bytes for taskCode.
     */
    com.google.protobuf.ByteString
        getTaskCodeBytes();

    /**
     * <code>string cmd = 3;</code>
     * @return The cmd.
     */
    java.lang.String getCmd();
    /**
     * <code>string cmd = 3;</code>
     * @return The bytes for cmd.
     */
    com.google.protobuf.ByteString
        getCmdBytes();

    /**
     * <code>map&lt;string, .google.protobuf.Any&gt; vars = 4;</code>
     */
    int getVarsCount();
    /**
     * <code>map&lt;string, .google.protobuf.Any&gt; vars = 4;</code>
     */
    boolean containsVars(
        java.lang.String key);
    /**
     * Use {@link #getVarsMap()} instead.
     */
    @java.lang.Deprecated
    java.util.Map<java.lang.String, com.google.protobuf.Any>
    getVars();
    /**
     * <code>map&lt;string, .google.protobuf.Any&gt; vars = 4;</code>
     */
    java.util.Map<java.lang.String, com.google.protobuf.Any>
    getVarsMap();
    /**
     * <code>map&lt;string, .google.protobuf.Any&gt; vars = 4;</code>
     */
    /* nullable */
com.google.protobuf.Any getVarsOrDefault(
        java.lang.String key,
        /* nullable */
com.google.protobuf.Any defaultValue);
    /**
     * <code>map&lt;string, .google.protobuf.Any&gt; vars = 4;</code>
     */
    com.google.protobuf.Any getVarsOrThrow(
        java.lang.String key);
  }
  /**
   * Protobuf type {@code proto.Any}
   */
  public static final class Any extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:proto.Any)
      AnyOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Any.newBuilder() to construct.
    private Any(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Any() {
      procCode_ = "";
      taskCode_ = "";
      cmd_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Any();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return proto.AnyProto.internal_static_proto_Any_descriptor;
    }

    @SuppressWarnings({"rawtypes"})
    @java.lang.Override
    protected com.google.protobuf.MapFieldReflectionAccessor internalGetMapFieldReflection(
        int number) {
      switch (number) {
        case 4:
          return internalGetVars();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return proto.AnyProto.internal_static_proto_Any_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              proto.AnyProto.Any.class, proto.AnyProto.Any.Builder.class);
    }

    public static final int PROCCODE_FIELD_NUMBER = 1;
    @SuppressWarnings("serial")
    private volatile java.lang.Object procCode_ = "";
    /**
     * <code>string procCode = 1;</code>
     * @return The procCode.
     */
    @java.lang.Override
    public java.lang.String getProcCode() {
      java.lang.Object ref = procCode_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        procCode_ = s;
        return s;
      }
    }
    /**
     * <code>string procCode = 1;</code>
     * @return The bytes for procCode.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getProcCodeBytes() {
      java.lang.Object ref = procCode_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        procCode_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TASKCODE_FIELD_NUMBER = 2;
    @SuppressWarnings("serial")
    private volatile java.lang.Object taskCode_ = "";
    /**
     * <code>string taskCode = 2;</code>
     * @return The taskCode.
     */
    @java.lang.Override
    public java.lang.String getTaskCode() {
      java.lang.Object ref = taskCode_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        taskCode_ = s;
        return s;
      }
    }
    /**
     * <code>string taskCode = 2;</code>
     * @return The bytes for taskCode.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getTaskCodeBytes() {
      java.lang.Object ref = taskCode_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        taskCode_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int CMD_FIELD_NUMBER = 3;
    @SuppressWarnings("serial")
    private volatile java.lang.Object cmd_ = "";
    /**
     * <code>string cmd = 3;</code>
     * @return The cmd.
     */
    @java.lang.Override
    public java.lang.String getCmd() {
      java.lang.Object ref = cmd_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        cmd_ = s;
        return s;
      }
    }
    /**
     * <code>string cmd = 3;</code>
     * @return The bytes for cmd.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getCmdBytes() {
      java.lang.Object ref = cmd_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        cmd_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int VARS_FIELD_NUMBER = 4;
    private static final class VarsDefaultEntryHolder {
      static final com.google.protobuf.MapEntry<
          java.lang.String, com.google.protobuf.Any> defaultEntry =
              com.google.protobuf.MapEntry
              .<java.lang.String, com.google.protobuf.Any>newDefaultInstance(
                  proto.AnyProto.internal_static_proto_Any_VarsEntry_descriptor, 
                  com.google.protobuf.WireFormat.FieldType.STRING,
                  "",
                  com.google.protobuf.WireFormat.FieldType.MESSAGE,
                  com.google.protobuf.Any.getDefaultInstance());
    }
    @SuppressWarnings("serial")
    private com.google.protobuf.MapField<
        java.lang.String, com.google.protobuf.Any> vars_;
    private com.google.protobuf.MapField<java.lang.String, com.google.protobuf.Any>
    internalGetVars() {
      if (vars_ == null) {
        return com.google.protobuf.MapField.emptyMapField(
            VarsDefaultEntryHolder.defaultEntry);
      }
      return vars_;
    }
    public int getVarsCount() {
      return internalGetVars().getMap().size();
    }
    /**
     * <code>map&lt;string, .google.protobuf.Any&gt; vars = 4;</code>
     */
    @java.lang.Override
    public boolean containsVars(
        java.lang.String key) {
      if (key == null) { throw new NullPointerException("map key"); }
      return internalGetVars().getMap().containsKey(key);
    }
    /**
     * Use {@link #getVarsMap()} instead.
     */
    @java.lang.Override
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, com.google.protobuf.Any> getVars() {
      return getVarsMap();
    }
    /**
     * <code>map&lt;string, .google.protobuf.Any&gt; vars = 4;</code>
     */
    @java.lang.Override
    public java.util.Map<java.lang.String, com.google.protobuf.Any> getVarsMap() {
      return internalGetVars().getMap();
    }
    /**
     * <code>map&lt;string, .google.protobuf.Any&gt; vars = 4;</code>
     */
    @java.lang.Override
    public /* nullable */
com.google.protobuf.Any getVarsOrDefault(
        java.lang.String key,
        /* nullable */
com.google.protobuf.Any defaultValue) {
      if (key == null) { throw new NullPointerException("map key"); }
      java.util.Map<java.lang.String, com.google.protobuf.Any> map =
          internalGetVars().getMap();
      return map.containsKey(key) ? map.get(key) : defaultValue;
    }
    /**
     * <code>map&lt;string, .google.protobuf.Any&gt; vars = 4;</code>
     */
    @java.lang.Override
    public com.google.protobuf.Any getVarsOrThrow(
        java.lang.String key) {
      if (key == null) { throw new NullPointerException("map key"); }
      java.util.Map<java.lang.String, com.google.protobuf.Any> map =
          internalGetVars().getMap();
      if (!map.containsKey(key)) {
        throw new java.lang.IllegalArgumentException();
      }
      return map.get(key);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(procCode_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, procCode_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(taskCode_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, taskCode_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(cmd_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, cmd_);
      }
      com.google.protobuf.GeneratedMessageV3
        .serializeStringMapTo(
          output,
          internalGetVars(),
          VarsDefaultEntryHolder.defaultEntry,
          4);
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(procCode_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, procCode_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(taskCode_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, taskCode_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(cmd_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, cmd_);
      }
      for (java.util.Map.Entry<java.lang.String, com.google.protobuf.Any> entry
           : internalGetVars().getMap().entrySet()) {
        com.google.protobuf.MapEntry<java.lang.String, com.google.protobuf.Any>
        vars__ = VarsDefaultEntryHolder.defaultEntry.newBuilderForType()
            .setKey(entry.getKey())
            .setValue(entry.getValue())
            .build();
        size += com.google.protobuf.CodedOutputStream
            .computeMessageSize(4, vars__);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof proto.AnyProto.Any)) {
        return super.equals(obj);
      }
      proto.AnyProto.Any other = (proto.AnyProto.Any) obj;

      if (!getProcCode()
          .equals(other.getProcCode())) return false;
      if (!getTaskCode()
          .equals(other.getTaskCode())) return false;
      if (!getCmd()
          .equals(other.getCmd())) return false;
      if (!internalGetVars().equals(
          other.internalGetVars())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + PROCCODE_FIELD_NUMBER;
      hash = (53 * hash) + getProcCode().hashCode();
      hash = (37 * hash) + TASKCODE_FIELD_NUMBER;
      hash = (53 * hash) + getTaskCode().hashCode();
      hash = (37 * hash) + CMD_FIELD_NUMBER;
      hash = (53 * hash) + getCmd().hashCode();
      if (!internalGetVars().getMap().isEmpty()) {
        hash = (37 * hash) + VARS_FIELD_NUMBER;
        hash = (53 * hash) + internalGetVars().hashCode();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static proto.AnyProto.Any parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static proto.AnyProto.Any parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static proto.AnyProto.Any parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static proto.AnyProto.Any parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static proto.AnyProto.Any parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static proto.AnyProto.Any parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static proto.AnyProto.Any parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static proto.AnyProto.Any parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static proto.AnyProto.Any parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static proto.AnyProto.Any parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static proto.AnyProto.Any parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static proto.AnyProto.Any parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(proto.AnyProto.Any prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code proto.Any}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:proto.Any)
        proto.AnyProto.AnyOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return proto.AnyProto.internal_static_proto_Any_descriptor;
      }

      @SuppressWarnings({"rawtypes"})
      protected com.google.protobuf.MapFieldReflectionAccessor internalGetMapFieldReflection(
          int number) {
        switch (number) {
          case 4:
            return internalGetVars();
          default:
            throw new RuntimeException(
                "Invalid map field number: " + number);
        }
      }
      @SuppressWarnings({"rawtypes"})
      protected com.google.protobuf.MapFieldReflectionAccessor internalGetMutableMapFieldReflection(
          int number) {
        switch (number) {
          case 4:
            return internalGetMutableVars();
          default:
            throw new RuntimeException(
                "Invalid map field number: " + number);
        }
      }
      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return proto.AnyProto.internal_static_proto_Any_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                proto.AnyProto.Any.class, proto.AnyProto.Any.Builder.class);
      }

      // Construct using proto.AnyProto.Any.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        procCode_ = "";
        taskCode_ = "";
        cmd_ = "";
        internalGetMutableVars().clear();
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return proto.AnyProto.internal_static_proto_Any_descriptor;
      }

      @java.lang.Override
      public proto.AnyProto.Any getDefaultInstanceForType() {
        return proto.AnyProto.Any.getDefaultInstance();
      }

      @java.lang.Override
      public proto.AnyProto.Any build() {
        proto.AnyProto.Any result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public proto.AnyProto.Any buildPartial() {
        proto.AnyProto.Any result = new proto.AnyProto.Any(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(proto.AnyProto.Any result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.procCode_ = procCode_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.taskCode_ = taskCode_;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.cmd_ = cmd_;
        }
        if (((from_bitField0_ & 0x00000008) != 0)) {
          result.vars_ = internalGetVars().build(VarsDefaultEntryHolder.defaultEntry);
        }
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof proto.AnyProto.Any) {
          return mergeFrom((proto.AnyProto.Any)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(proto.AnyProto.Any other) {
        if (other == proto.AnyProto.Any.getDefaultInstance()) return this;
        if (!other.getProcCode().isEmpty()) {
          procCode_ = other.procCode_;
          bitField0_ |= 0x00000001;
          onChanged();
        }
        if (!other.getTaskCode().isEmpty()) {
          taskCode_ = other.taskCode_;
          bitField0_ |= 0x00000002;
          onChanged();
        }
        if (!other.getCmd().isEmpty()) {
          cmd_ = other.cmd_;
          bitField0_ |= 0x00000004;
          onChanged();
        }
        internalGetMutableVars().mergeFrom(
            other.internalGetVars());
        bitField0_ |= 0x00000008;
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                procCode_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000001;
                break;
              } // case 10
              case 18: {
                taskCode_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000002;
                break;
              } // case 18
              case 26: {
                cmd_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000004;
                break;
              } // case 26
              case 34: {
                com.google.protobuf.MapEntry<java.lang.String, com.google.protobuf.Any>
                vars__ = input.readMessage(
                    VarsDefaultEntryHolder.defaultEntry.getParserForType(), extensionRegistry);
                internalGetMutableVars().ensureBuilderMap().put(
                    vars__.getKey(), vars__.getValue());
                bitField0_ |= 0x00000008;
                break;
              } // case 34
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private java.lang.Object procCode_ = "";
      /**
       * <code>string procCode = 1;</code>
       * @return The procCode.
       */
      public java.lang.String getProcCode() {
        java.lang.Object ref = procCode_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          procCode_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string procCode = 1;</code>
       * @return The bytes for procCode.
       */
      public com.google.protobuf.ByteString
          getProcCodeBytes() {
        java.lang.Object ref = procCode_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          procCode_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string procCode = 1;</code>
       * @param value The procCode to set.
       * @return This builder for chaining.
       */
      public Builder setProcCode(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        procCode_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>string procCode = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearProcCode() {
        procCode_ = getDefaultInstance().getProcCode();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      /**
       * <code>string procCode = 1;</code>
       * @param value The bytes for procCode to set.
       * @return This builder for chaining.
       */
      public Builder setProcCodeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        procCode_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }

      private java.lang.Object taskCode_ = "";
      /**
       * <code>string taskCode = 2;</code>
       * @return The taskCode.
       */
      public java.lang.String getTaskCode() {
        java.lang.Object ref = taskCode_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          taskCode_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string taskCode = 2;</code>
       * @return The bytes for taskCode.
       */
      public com.google.protobuf.ByteString
          getTaskCodeBytes() {
        java.lang.Object ref = taskCode_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          taskCode_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string taskCode = 2;</code>
       * @param value The taskCode to set.
       * @return This builder for chaining.
       */
      public Builder setTaskCode(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        taskCode_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>string taskCode = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearTaskCode() {
        taskCode_ = getDefaultInstance().getTaskCode();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
        return this;
      }
      /**
       * <code>string taskCode = 2;</code>
       * @param value The bytes for taskCode to set.
       * @return This builder for chaining.
       */
      public Builder setTaskCodeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        taskCode_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }

      private java.lang.Object cmd_ = "";
      /**
       * <code>string cmd = 3;</code>
       * @return The cmd.
       */
      public java.lang.String getCmd() {
        java.lang.Object ref = cmd_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          cmd_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string cmd = 3;</code>
       * @return The bytes for cmd.
       */
      public com.google.protobuf.ByteString
          getCmdBytes() {
        java.lang.Object ref = cmd_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          cmd_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string cmd = 3;</code>
       * @param value The cmd to set.
       * @return This builder for chaining.
       */
      public Builder setCmd(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        cmd_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <code>string cmd = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearCmd() {
        cmd_ = getDefaultInstance().getCmd();
        bitField0_ = (bitField0_ & ~0x00000004);
        onChanged();
        return this;
      }
      /**
       * <code>string cmd = 3;</code>
       * @param value The bytes for cmd to set.
       * @return This builder for chaining.
       */
      public Builder setCmdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        cmd_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }

      private static final class VarsConverter implements com.google.protobuf.MapFieldBuilder.Converter<java.lang.String, com.google.protobuf.AnyOrBuilder, com.google.protobuf.Any> {
        @java.lang.Override
        public com.google.protobuf.Any build(com.google.protobuf.AnyOrBuilder val) {
          if (val instanceof com.google.protobuf.Any) { return (com.google.protobuf.Any) val; }
          return ((com.google.protobuf.Any.Builder) val).build();
        }

        @java.lang.Override
        public com.google.protobuf.MapEntry<java.lang.String, com.google.protobuf.Any> defaultEntry() {
          return VarsDefaultEntryHolder.defaultEntry;
        }
      };
      private static final VarsConverter varsConverter = new VarsConverter();

      private com.google.protobuf.MapFieldBuilder<
          java.lang.String, com.google.protobuf.AnyOrBuilder, com.google.protobuf.Any, com.google.protobuf.Any.Builder> vars_;
      private com.google.protobuf.MapFieldBuilder<java.lang.String, com.google.protobuf.AnyOrBuilder, com.google.protobuf.Any, com.google.protobuf.Any.Builder>
          internalGetVars() {
        if (vars_ == null) {
          return new com.google.protobuf.MapFieldBuilder<>(varsConverter);
        }
        return vars_;
      }
      private com.google.protobuf.MapFieldBuilder<java.lang.String, com.google.protobuf.AnyOrBuilder, com.google.protobuf.Any, com.google.protobuf.Any.Builder>
          internalGetMutableVars() {
        if (vars_ == null) {
          vars_ = new com.google.protobuf.MapFieldBuilder<>(varsConverter);
        }
        bitField0_ |= 0x00000008;
        onChanged();
        return vars_;
      }
      public int getVarsCount() {
        return internalGetVars().ensureBuilderMap().size();
      }
      /**
       * <code>map&lt;string, .google.protobuf.Any&gt; vars = 4;</code>
       */
      @java.lang.Override
      public boolean containsVars(
          java.lang.String key) {
        if (key == null) { throw new NullPointerException("map key"); }
        return internalGetVars().ensureBuilderMap().containsKey(key);
      }
      /**
       * Use {@link #getVarsMap()} instead.
       */
      @java.lang.Override
      @java.lang.Deprecated
      public java.util.Map<java.lang.String, com.google.protobuf.Any> getVars() {
        return getVarsMap();
      }
      /**
       * <code>map&lt;string, .google.protobuf.Any&gt; vars = 4;</code>
       */
      @java.lang.Override
      public java.util.Map<java.lang.String, com.google.protobuf.Any> getVarsMap() {
        return internalGetVars().getImmutableMap();
      }
      /**
       * <code>map&lt;string, .google.protobuf.Any&gt; vars = 4;</code>
       */
      @java.lang.Override
      public /* nullable */
com.google.protobuf.Any getVarsOrDefault(
          java.lang.String key,
          /* nullable */
com.google.protobuf.Any defaultValue) {
        if (key == null) { throw new NullPointerException("map key"); }
        java.util.Map<java.lang.String, com.google.protobuf.AnyOrBuilder> map = internalGetMutableVars().ensureBuilderMap();
        return map.containsKey(key) ? varsConverter.build(map.get(key)) : defaultValue;
      }
      /**
       * <code>map&lt;string, .google.protobuf.Any&gt; vars = 4;</code>
       */
      @java.lang.Override
      public com.google.protobuf.Any getVarsOrThrow(
          java.lang.String key) {
        if (key == null) { throw new NullPointerException("map key"); }
        java.util.Map<java.lang.String, com.google.protobuf.AnyOrBuilder> map = internalGetMutableVars().ensureBuilderMap();
        if (!map.containsKey(key)) {
          throw new java.lang.IllegalArgumentException();
        }
        return varsConverter.build(map.get(key));
      }
      public Builder clearVars() {
        bitField0_ = (bitField0_ & ~0x00000008);
        internalGetMutableVars().clear();
        return this;
      }
      /**
       * <code>map&lt;string, .google.protobuf.Any&gt; vars = 4;</code>
       */
      public Builder removeVars(
          java.lang.String key) {
        if (key == null) { throw new NullPointerException("map key"); }
        internalGetMutableVars().ensureBuilderMap()
            .remove(key);
        return this;
      }
      /**
       * Use alternate mutation accessors instead.
       */
      @java.lang.Deprecated
      public java.util.Map<java.lang.String, com.google.protobuf.Any>
          getMutableVars() {
        bitField0_ |= 0x00000008;
        return internalGetMutableVars().ensureMessageMap();
      }
      /**
       * <code>map&lt;string, .google.protobuf.Any&gt; vars = 4;</code>
       */
      public Builder putVars(
          java.lang.String key,
          com.google.protobuf.Any value) {
        if (key == null) { throw new NullPointerException("map key"); }
        if (value == null) { throw new NullPointerException("map value"); }
        internalGetMutableVars().ensureBuilderMap()
            .put(key, value);
        bitField0_ |= 0x00000008;
        return this;
      }
      /**
       * <code>map&lt;string, .google.protobuf.Any&gt; vars = 4;</code>
       */
      public Builder putAllVars(
          java.util.Map<java.lang.String, com.google.protobuf.Any> values) {
        for (java.util.Map.Entry<java.lang.String, com.google.protobuf.Any> e : values.entrySet()) {
          if (e.getKey() == null || e.getValue() == null) {
            throw new NullPointerException();
          }
        }
        internalGetMutableVars().ensureBuilderMap()
            .putAll(values);
        bitField0_ |= 0x00000008;
        return this;
      }
      /**
       * <code>map&lt;string, .google.protobuf.Any&gt; vars = 4;</code>
       */
      public com.google.protobuf.Any.Builder putVarsBuilderIfAbsent(
          java.lang.String key) {
        java.util.Map<java.lang.String, com.google.protobuf.AnyOrBuilder> builderMap = internalGetMutableVars().ensureBuilderMap();
        com.google.protobuf.AnyOrBuilder entry = builderMap.get(key);
        if (entry == null) {
          entry = com.google.protobuf.Any.newBuilder();
          builderMap.put(key, entry);
        }
        if (entry instanceof com.google.protobuf.Any) {
          entry = ((com.google.protobuf.Any) entry).toBuilder();
          builderMap.put(key, entry);
        }
        return (com.google.protobuf.Any.Builder) entry;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:proto.Any)
    }

    // @@protoc_insertion_point(class_scope:proto.Any)
    private static final proto.AnyProto.Any DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new proto.AnyProto.Any();
    }

    public static proto.AnyProto.Any getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Any>
        PARSER = new com.google.protobuf.AbstractParser<Any>() {
      @java.lang.Override
      public Any parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<Any> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Any> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public proto.AnyProto.Any getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_Any_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_proto_Any_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_Any_VarsEntry_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_proto_Any_VarsEntry_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\tany.proto\022\005proto\032\031google/protobuf/any." +
      "proto\"\235\001\n\003Any\022\020\n\010procCode\030\001 \001(\t\022\020\n\010taskC" +
      "ode\030\002 \001(\t\022\013\n\003cmd\030\003 \001(\t\022\"\n\004vars\030\004 \003(\0132\024.p" +
      "roto.Any.VarsEntry\032A\n\tVarsEntry\022\013\n\003key\030\001" +
      " \001(\t\022#\n\005value\030\002 \001(\0132\024.google.protobuf.An" +
      "y:\0028\001B\021\n\005protoB\010AnyProtob\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.AnyProto.getDescriptor(),
        });
    internal_static_proto_Any_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_proto_Any_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_proto_Any_descriptor,
        new java.lang.String[] { "ProcCode", "TaskCode", "Cmd", "Vars", });
    internal_static_proto_Any_VarsEntry_descriptor =
      internal_static_proto_Any_descriptor.getNestedTypes().get(0);
    internal_static_proto_Any_VarsEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_proto_Any_VarsEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    com.google.protobuf.AnyProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
