// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: run.proto

package com.onlinecode.admin.proto;

public final class RunProto {
  private RunProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface RunOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.onlinecode.admin.proto.Run)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string procCode = 1;</code>
     * @return The procCode.
     */
    java.lang.String getProcCode();
    /**
     * <code>string procCode = 1;</code>
     * @return The bytes for procCode.
     */
    com.google.protobuf.ByteString
        getProcCodeBytes();

    /**
     * <code>string taskCode = 2;</code>
     * @return The taskCode.
     */
    java.lang.String getTaskCode();
    /**
     * <code>string taskCode = 2;</code>
     * @return The bytes for taskCode.
     */
    com.google.protobuf.ByteString
        getTaskCodeBytes();

    /**
     * <code>string cmd = 3;</code>
     * @return The cmd.
     */
    java.lang.String getCmd();
    /**
     * <code>string cmd = 3;</code>
     * @return The bytes for cmd.
     */
    com.google.protobuf.ByteString
        getCmdBytes();

    /**
     * <code>string vars = 4;</code>
     * @return The vars.
     */
    java.lang.String getVars();
    /**
     * <code>string vars = 4;</code>
     * @return The bytes for vars.
     */
    com.google.protobuf.ByteString
        getVarsBytes();
  }
  /**
   * Protobuf type {@code com.onlinecode.admin.proto.Run}
   */
  public static final class Run extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.onlinecode.admin.proto.Run)
      RunOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Run.newBuilder() to construct.
    private Run(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Run() {
      procCode_ = "";
      taskCode_ = "";
      cmd_ = "";
      vars_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Run();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Run(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              procCode_ = s;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              taskCode_ = s;
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              cmd_ = s;
              break;
            }
            case 34: {
              java.lang.String s = input.readStringRequireUtf8();

              vars_ = s;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.onlinecode.admin.proto.RunProto.internal_static_com_onlinecode_admin_proto_Run_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.onlinecode.admin.proto.RunProto.internal_static_com_onlinecode_admin_proto_Run_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.onlinecode.admin.proto.RunProto.Run.class, com.onlinecode.admin.proto.RunProto.Run.Builder.class);
    }

    public static final int PROCCODE_FIELD_NUMBER = 1;
    private volatile java.lang.Object procCode_;
    /**
     * <code>string procCode = 1;</code>
     * @return The procCode.
     */
    @java.lang.Override
    public java.lang.String getProcCode() {
      java.lang.Object ref = procCode_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        procCode_ = s;
        return s;
      }
    }
    /**
     * <code>string procCode = 1;</code>
     * @return The bytes for procCode.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getProcCodeBytes() {
      java.lang.Object ref = procCode_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        procCode_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TASKCODE_FIELD_NUMBER = 2;
    private volatile java.lang.Object taskCode_;
    /**
     * <code>string taskCode = 2;</code>
     * @return The taskCode.
     */
    @java.lang.Override
    public java.lang.String getTaskCode() {
      java.lang.Object ref = taskCode_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        taskCode_ = s;
        return s;
      }
    }
    /**
     * <code>string taskCode = 2;</code>
     * @return The bytes for taskCode.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getTaskCodeBytes() {
      java.lang.Object ref = taskCode_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        taskCode_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int CMD_FIELD_NUMBER = 3;
    private volatile java.lang.Object cmd_;
    /**
     * <code>string cmd = 3;</code>
     * @return The cmd.
     */
    @java.lang.Override
    public java.lang.String getCmd() {
      java.lang.Object ref = cmd_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        cmd_ = s;
        return s;
      }
    }
    /**
     * <code>string cmd = 3;</code>
     * @return The bytes for cmd.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getCmdBytes() {
      java.lang.Object ref = cmd_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        cmd_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int VARS_FIELD_NUMBER = 4;
    private volatile java.lang.Object vars_;
    /**
     * <code>string vars = 4;</code>
     * @return The vars.
     */
    @java.lang.Override
    public java.lang.String getVars() {
      java.lang.Object ref = vars_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        vars_ = s;
        return s;
      }
    }
    /**
     * <code>string vars = 4;</code>
     * @return The bytes for vars.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getVarsBytes() {
      java.lang.Object ref = vars_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        vars_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(procCode_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, procCode_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(taskCode_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, taskCode_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(cmd_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, cmd_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(vars_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, vars_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(procCode_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, procCode_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(taskCode_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, taskCode_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(cmd_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, cmd_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(vars_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, vars_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.onlinecode.admin.proto.RunProto.Run)) {
        return super.equals(obj);
      }
      com.onlinecode.admin.proto.RunProto.Run other = (com.onlinecode.admin.proto.RunProto.Run) obj;

      if (!getProcCode()
          .equals(other.getProcCode())) return false;
      if (!getTaskCode()
          .equals(other.getTaskCode())) return false;
      if (!getCmd()
          .equals(other.getCmd())) return false;
      if (!getVars()
          .equals(other.getVars())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + PROCCODE_FIELD_NUMBER;
      hash = (53 * hash) + getProcCode().hashCode();
      hash = (37 * hash) + TASKCODE_FIELD_NUMBER;
      hash = (53 * hash) + getTaskCode().hashCode();
      hash = (37 * hash) + CMD_FIELD_NUMBER;
      hash = (53 * hash) + getCmd().hashCode();
      hash = (37 * hash) + VARS_FIELD_NUMBER;
      hash = (53 * hash) + getVars().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.onlinecode.admin.proto.RunProto.Run parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.onlinecode.admin.proto.RunProto.Run parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.onlinecode.admin.proto.RunProto.Run parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.onlinecode.admin.proto.RunProto.Run parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.onlinecode.admin.proto.RunProto.Run parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.onlinecode.admin.proto.RunProto.Run parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.onlinecode.admin.proto.RunProto.Run parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.onlinecode.admin.proto.RunProto.Run parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.onlinecode.admin.proto.RunProto.Run parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.onlinecode.admin.proto.RunProto.Run parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.onlinecode.admin.proto.RunProto.Run parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.onlinecode.admin.proto.RunProto.Run parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.onlinecode.admin.proto.RunProto.Run prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.onlinecode.admin.proto.Run}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.onlinecode.admin.proto.Run)
        com.onlinecode.admin.proto.RunProto.RunOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.onlinecode.admin.proto.RunProto.internal_static_com_onlinecode_admin_proto_Run_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.onlinecode.admin.proto.RunProto.internal_static_com_onlinecode_admin_proto_Run_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.onlinecode.admin.proto.RunProto.Run.class, com.onlinecode.admin.proto.RunProto.Run.Builder.class);
      }

      // Construct using com.onlinecode.admin.proto.RunProto.Run.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        procCode_ = "";

        taskCode_ = "";

        cmd_ = "";

        vars_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.onlinecode.admin.proto.RunProto.internal_static_com_onlinecode_admin_proto_Run_descriptor;
      }

      @java.lang.Override
      public com.onlinecode.admin.proto.RunProto.Run getDefaultInstanceForType() {
        return com.onlinecode.admin.proto.RunProto.Run.getDefaultInstance();
      }

      @java.lang.Override
      public com.onlinecode.admin.proto.RunProto.Run build() {
        com.onlinecode.admin.proto.RunProto.Run result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.onlinecode.admin.proto.RunProto.Run buildPartial() {
        com.onlinecode.admin.proto.RunProto.Run result = new com.onlinecode.admin.proto.RunProto.Run(this);
        result.procCode_ = procCode_;
        result.taskCode_ = taskCode_;
        result.cmd_ = cmd_;
        result.vars_ = vars_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.onlinecode.admin.proto.RunProto.Run) {
          return mergeFrom((com.onlinecode.admin.proto.RunProto.Run)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.onlinecode.admin.proto.RunProto.Run other) {
        if (other == com.onlinecode.admin.proto.RunProto.Run.getDefaultInstance()) return this;
        if (!other.getProcCode().isEmpty()) {
          procCode_ = other.procCode_;
          onChanged();
        }
        if (!other.getTaskCode().isEmpty()) {
          taskCode_ = other.taskCode_;
          onChanged();
        }
        if (!other.getCmd().isEmpty()) {
          cmd_ = other.cmd_;
          onChanged();
        }
        if (!other.getVars().isEmpty()) {
          vars_ = other.vars_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.onlinecode.admin.proto.RunProto.Run parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.onlinecode.admin.proto.RunProto.Run) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object procCode_ = "";
      /**
       * <code>string procCode = 1;</code>
       * @return The procCode.
       */
      public java.lang.String getProcCode() {
        java.lang.Object ref = procCode_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          procCode_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string procCode = 1;</code>
       * @return The bytes for procCode.
       */
      public com.google.protobuf.ByteString
          getProcCodeBytes() {
        java.lang.Object ref = procCode_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          procCode_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string procCode = 1;</code>
       * @param value The procCode to set.
       * @return This builder for chaining.
       */
      public Builder setProcCode(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        procCode_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string procCode = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearProcCode() {
        
        procCode_ = getDefaultInstance().getProcCode();
        onChanged();
        return this;
      }
      /**
       * <code>string procCode = 1;</code>
       * @param value The bytes for procCode to set.
       * @return This builder for chaining.
       */
      public Builder setProcCodeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        procCode_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object taskCode_ = "";
      /**
       * <code>string taskCode = 2;</code>
       * @return The taskCode.
       */
      public java.lang.String getTaskCode() {
        java.lang.Object ref = taskCode_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          taskCode_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string taskCode = 2;</code>
       * @return The bytes for taskCode.
       */
      public com.google.protobuf.ByteString
          getTaskCodeBytes() {
        java.lang.Object ref = taskCode_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          taskCode_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string taskCode = 2;</code>
       * @param value The taskCode to set.
       * @return This builder for chaining.
       */
      public Builder setTaskCode(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        taskCode_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string taskCode = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearTaskCode() {
        
        taskCode_ = getDefaultInstance().getTaskCode();
        onChanged();
        return this;
      }
      /**
       * <code>string taskCode = 2;</code>
       * @param value The bytes for taskCode to set.
       * @return This builder for chaining.
       */
      public Builder setTaskCodeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        taskCode_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object cmd_ = "";
      /**
       * <code>string cmd = 3;</code>
       * @return The cmd.
       */
      public java.lang.String getCmd() {
        java.lang.Object ref = cmd_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          cmd_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string cmd = 3;</code>
       * @return The bytes for cmd.
       */
      public com.google.protobuf.ByteString
          getCmdBytes() {
        java.lang.Object ref = cmd_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          cmd_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string cmd = 3;</code>
       * @param value The cmd to set.
       * @return This builder for chaining.
       */
      public Builder setCmd(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        cmd_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string cmd = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearCmd() {
        
        cmd_ = getDefaultInstance().getCmd();
        onChanged();
        return this;
      }
      /**
       * <code>string cmd = 3;</code>
       * @param value The bytes for cmd to set.
       * @return This builder for chaining.
       */
      public Builder setCmdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        cmd_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object vars_ = "";
      /**
       * <code>string vars = 4;</code>
       * @return The vars.
       */
      public java.lang.String getVars() {
        java.lang.Object ref = vars_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          vars_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string vars = 4;</code>
       * @return The bytes for vars.
       */
      public com.google.protobuf.ByteString
          getVarsBytes() {
        java.lang.Object ref = vars_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          vars_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string vars = 4;</code>
       * @param value The vars to set.
       * @return This builder for chaining.
       */
      public Builder setVars(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        vars_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string vars = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearVars() {
        
        vars_ = getDefaultInstance().getVars();
        onChanged();
        return this;
      }
      /**
       * <code>string vars = 4;</code>
       * @param value The bytes for vars to set.
       * @return This builder for chaining.
       */
      public Builder setVarsBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        vars_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.onlinecode.admin.proto.Run)
    }

    // @@protoc_insertion_point(class_scope:com.onlinecode.admin.proto.Run)
    private static final com.onlinecode.admin.proto.RunProto.Run DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.onlinecode.admin.proto.RunProto.Run();
    }

    public static com.onlinecode.admin.proto.RunProto.Run getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Run>
        PARSER = new com.google.protobuf.AbstractParser<Run>() {
      @java.lang.Override
      public Run parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Run(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Run> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Run> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.onlinecode.admin.proto.RunProto.Run getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_onlinecode_admin_proto_Run_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_onlinecode_admin_proto_Run_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\trun.proto\022\032com.onlinecode.admin.proto\"" +
      "D\n\003Run\022\020\n\010procCode\030\001 \001(\t\022\020\n\010taskCode\030\002 \001" +
      "(\t\022\013\n\003cmd\030\003 \001(\t\022\014\n\004vars\030\004 \001(\tB&\n\032com.onl" +
      "inecode.admin.protoB\010RunProtob\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_com_onlinecode_admin_proto_Run_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_onlinecode_admin_proto_Run_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_onlinecode_admin_proto_Run_descriptor,
        new java.lang.String[] { "ProcCode", "TaskCode", "Cmd", "Vars", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
